# OSS-Fuzz project metadata
homepage: https://github.com/wooseok-dev/test-pub
language: c++
main_repo: https://github.com/wooseok-dev/test-pub
primary_contact: replace-me@example.com
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
architectures:
  - x86_64

